# Generated by Django 5.2.7 on 2025-10-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0014_rename_added_at_wishlist_created_at_cart_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age_range',
            field=models.CharField(blank=True, choices=[('0-6', '0-6 months'), ('6-12', '6-12 months'), ('1-2', '1-2 years'), ('2-3', '2-3 years'), ('all', 'All Ages')], default='all', max_length=5, null=True),
        ),
    ]
